package com.github.h0ru5.neopixel;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : rpi_ws281x\dma.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class dma_page extends Structure {
	/** C type : dma_page* */
	public dma_page.ByReference next;
	/** C type : dma_page* */
	public dma_page.ByReference prev;
	/** C type : void* */
	public Pointer addr;
	public dma_page() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("next", "prev", "addr");
	}
	/**
	 * @param next C type : dma_page*<br>
	 * @param prev C type : dma_page*<br>
	 * @param addr C type : void*
	 */
	public dma_page(dma_page.ByReference next, dma_page.ByReference prev, Pointer addr) {
		super();
		this.next = next;
		this.prev = prev;
		this.addr = addr;
	}
	public static class ByReference extends dma_page implements Structure.ByReference {
		
	};
	public static class ByValue extends dma_page implements Structure.ByValue {
		
	};
}
