package com.github.h0ru5.neopixel;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : rpi_ws281x\pwm.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pwm_t extends Structure {
	public int ctl;
	public int sta;
	public int dmac;
	public int resvd_0x0c;
	public int rng1;
	public int dat1;
	public int fif1;
	public int resvd_0x1c;
	public int rng2;
	public int dat2;
	public pwm_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ctl", "sta", "dmac", "resvd_0x0c", "rng1", "dat1", "fif1", "resvd_0x1c", "rng2", "dat2");
	}
	public static class ByReference extends pwm_t implements Structure.ByReference {
		
	};
	public static class ByValue extends pwm_t implements Structure.ByValue {
		
	};
}
